# Generated by Django 4.2.6 on 2023-10-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('contno', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('occupation', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=200)),
                ('id_issue', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('issue_state', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('add_type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('nation', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
